# UBAH LINE 3 SESUAI DENGAN NAMA DATABASE KALIAN e.g 'USE db_sifiks'

USE nama_database;
INSERT INTO doctor_specializations (degree, name, created_at, updated_at)
VALUES
       ('Sp.A', 'Spesialis Anak', NOW(), NOW()),
       ('Sp.An', 'Spesialis Anestesiologi dan Terapi Intensif', NOW(), NOW()),
       ('Sp.And', 'Spesialis Andrologi', NOW(), NOW()),
       ('Sp.Ak', 'Spesialis Akupuntur', NOW(), NOW()),
       ('Sp.B', 'Spesialis Bedah', NOW(), NOW()),
       ('Sp.BA', 'Spesialis Bedah Anak', NOW(), NOW()),
       ('Sp.BM', 'Spesialis Bedah Mulut dan Maksilofasial', NOW(), NOW()),
       ('Sp.BP-RE', 'Spesialis Bedah Plastik Rekonstruksi dan Estetik', NOW(), NOW()),
       ('Sp.BS', 'Spesialis Bedah Saraf', NOW(), NOW()),
       ('Sp.BTKV', 'Spesialis Bedah Toraks dan Kardiovaskular', NOW(), NOW()),
       ('Sp.F', 'Spesialis Forensik dan Medikolegal', NOW(), NOW()),
       ('Sp.FK', 'Spesialis Farmakologi Klinik', NOW(), NOW()),
       ('Sp.GK', 'Spesialis Gizi Klinik', NOW(), NOW()),
       ('Sp.JP', 'Spesialis Jantung dan Pembuluh Darah', NOW(), NOW()),
       ('Sp.KFR', 'Spesialis Kedokteran Fisik dan Rehabilitasi', NOW(), NOW()),
       ('Sp.KG', 'Spesialis Konservasi Gigi', NOW(), NOW()),
       ('Sp.KGA', 'Spesialis Kedokteran Gigi Anak', NOW(), NOW()),
       ('Sp.KJ', 'Spesialis Kedokteran Jiwa atau Psikiatri', NOW(), NOW()),
       ('Sp.KP', 'Spesialis Kedokteran Penerbangan', NOW(), NOW()),
       ('Sp.KK', 'Spesialis Penyakit Kulit dan Kelamin', NOW(), NOW()),
       ('Sp.EM', 'Spesialis Emergency Medic', NOW(), NOW()),
       ('Sp.KN', 'Spesialis Kedokteran Nuklir', NOW(), NOW()),
       ('Sp.KO', 'Spesialis Kedokteran Olahraga', NOW(), NOW()),
       ('Sp.LP', 'Spesialis Layanan Primer', NOW(), NOW()),
       ('Sp.M', 'Spesialis Mata', NOW(), NOW()),
       ('Sp.MK', 'Spesialis Mikrobiologi Klinik', NOW(), NOW()),
       ('Sp.OG', 'Spesialis Obstetri & Ginekologi (Kebidanan dan Kandungan)', NOW(), NOW()),
       ('Sp.Ok', 'Spesialis Kedokteran Okupasi (Kerja)', NOW(), NOW()),
       ('Sp.Onk.Rad', 'Spesialis Onkologi Radiasi', NOW(), NOW()),
       ('Sp.Ort', 'Spesialis Ortodonsia', NOW(), NOW()),
       ('Sp.OT', 'Spesialis Bedah Orthopaedi dan Traumatologi', NOW(), NOW()),
       ('Sp.P', 'Spesialis Pulmonologi dan Kedokteran Respirasi (Paru)', NOW(), NOW()),
       ('Sp.ParK', 'Spesialis Parasitologi Klinik', NOW(), NOW()),
       ('Sp.Perio', 'Spesialis Periodonsia', NOW(), NOW()),
       ('Sp.PA', 'Spesialis Patologi Anatomi', NOW(), NOW()),
       ('Sp.PD', 'Spesialis Penyakit Dalam', NOW(), NOW()),
       ('Sp.PK', 'Spesialis Patologi Klinik', NOW(), NOW()),
       ('Sp.PM', 'Spesialis Penyakit Mulut (Dokter Gigi)', NOW(), NOW()),
       ('Sp.Pros', 'Spesialis Prostodonsia', NOW(), NOW()),
       ('Sp.Rad', 'Spesialis Radiologi', NOW(), NOW()),
       ('Sp.RKG', 'Spesialis Radiologi Kedokteran Gigi', NOW(), NOW()),
       ('Sp.S', 'Spesialis Saraf', NOW(), NOW()),
       ('Sp.THT-KL', 'Spesialis Telinga Hidung Tenggorok-Bedah Kepala Leher', NOW(), NOW()),
       ('Sp.U', 'Spesialis Urologi', NOW(), NOW()),
       ('Sp.Ger', 'Spesialis Geriatri', NOW(), NOW());